name: Create Badges

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize]

jobs:
  create_badges:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build and Test
        run: |
          echo "Simulating build..."
          echo "Simulating tests..."
        
      - name: Create Multiple Badges
        uses: ./.github/workflows/BYOB.yml
        with:
          name: build-status
          label: 'Build Status'
          icon: 'check-circle'
          status: ${{ steps.build-and-test.outputs.result }}
          color: green
          github_token: ${{ secrets.GITHUB_TOKEN }}

          name: test-results
          label: 'Test Results'
          icon: 'xmark-circle'
          status: ${{ steps.build-and-test.outputs.result }}
          color: red
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Badges to PR
        if: github.event_name == 'pull_request'
        uses: peaceiris/actions-upload-artifact@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-name: badge-images
          upload-type: zip
          upload-path: badges.zip
          description: 'Badges for PR Review'
          branch: ${{ github.head_ref }}
