name: BYOB

on:
    schedule:
        - cron: "*/5 * * * *"

jobs:
    badge_job:
        runs-on: ubuntu-latest
        steps:
            - name: Bring Your Own Badge
              uses: RubbaBoy/BYOB@v1.3.0
              with:
                  NAME: contributions-welcome
                  LABEL: "Contributions Welcome"
                  ICON: "github"
                  STATUS: "Contributions welcome"
                  COLOR: green
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Read LICENSE file
              id: license
              run: |
                  echo "::set-env name=LICENSE_CONTENT::$(cat ${GITHUB_WORKSPACE}/LICENSE)"

            - name: Bring Your Own Badge
              uses: RubbaBoy/BYOB@v1.3.0
              with:
                  NAME: license
                  LABEL: "License"
                  ICON: "license"
                  STATUS: ${{ env.LICENSE_CONTENT | truncate:50 }}
                  COLOR: blue
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
